Repository redBorder/cookbook-rb-selinux, pull requests merged in 2024-05, with the labels that each got.

#7 Update README.md
  README.md
Labels: documentation, size/XS, kind/documentation

#10 Update README and metadata
  .github/workflows/rpm.yml
  README.md
  resources/metadata.rb
Labels: documentation, kind/documentation, size/M, no-release

#11 Update rpm.yml
  .github/workflows/rpm.yml
Labels: kind/documentation, no-release, size/S

#13 Update metadata README and rpm build process
  .github/workflows/rpm.yml
  Gemfile
  resources/CHANGELOG.md
  resources/metadata.rb
Labels: kind/documentation, size/M

#14 Update rpm.yml
  .github/workflows/rpm.yml
Labels: size/XS, kind/documentation

#23 Line up contributors to development
  .all-contributorsrc
  README.md
Labels: documentation, kind/documentation, size/M

#24 Improvement/fix cookbook lint
  resources/providers/config.rb
  resources/recipes/configure_solo.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: enhancement, kind/bug, size/M, lint, refactor

#25 Release 0.1.2
  CHANGELOG.md
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/configure_solo.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: kind/documentation, size/M
