Repository redBorder/cookbook-rb-selinux, pull requests merged in 2024-04, with the labels that each got.

#4 split into redborder-selinux
  packaging/rpm/cookbook-rb-selinux.spec
  resources/files/redborder-manager.te
  resources/providers/config.rb
Labels: kind/bug, size/L

#5 Release 0.1.0
  CHANGELOG.md
  packaging/rpm/cookbook-rb-selinux.spec
  resources/metadata.rb
Labels: size/XS, release, kind/documentation

#6 Added ../rpm.yml to .github/workflows/
  .github/workflows/rpm.yml
Labels: kind/feature, size/M
